wandb_version: 1

optimization:lr:
  desc: null
  value: 0.0001
optimization:iters:
  desc: null
  value: 1000
dataset:dataset:
  desc: null
  value: ucf-crime
model:kernel_sizes:
  desc: null
  value:
  - 1
  - 1
  - 1
model:channel_ratios:
  desc: null
  value:
  - 16
  - 32
triplet_loss:abn_ratio_sample:
  desc: null
  value: 0.1
triplet_loss:abn_ratio_batch:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.12.0
    cli_version: 0.18.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729440441
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 4
      - 13
      - 16
      - 23
      - 42
      - 55
      4: 3.12.0
      5: 0.18.3
      8:
      - 5
      13: darwin-arm64
