_wandb:
    value:
        cli_version: 0.18.3
        code_path: code/main.py
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.0
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
dataset:dataset:
    value: ucf-crime
model:channel_ratios:
    value:
        - 16
        - 32
model:kernel_sizes:
    value:
        - 1
        - 1
        - 1
optimization:iters:
    value: 1000
optimization:lr:
    value: 0.0001
triplet_loss:abn_ratio_batch:
    value: 0.2
triplet_loss:abn_ratio_sample:
    value: 0.1
